charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/README.md
charts/k8s-watcher/templates/_proxy_conf.tpl
charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/values.yaml

Tested:
`helm template . --set apiKey=test --set proxy.enabled=false --set proxy.https=https://test.com --set proxy.http=http://aaa.com`
`helm template . --set apiKey=test --set proxy.enabled=true --set proxy.https=https://test.com --set proxy.http=http://aaa.com`
`helm template . --set apiKey=test --set proxy.enabled=true --set proxy.https=https://test.com`
`helm template . --set apiKey=test --set proxy.enabled=true  --set proxy.http=http://aaa.com`
`helm template . --set apiKey=test --set proxy.enabled=true  --set proxy.https=https://aaa.com --set proxy.no_proxy=*aaa.io`

Add http(s) proxy support

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/README.md
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/templates/secret-credentials.yaml
charts/k8s-watcher/values.yaml

These changes allow using an existing secret resource for the Komodor `apiKey` instead of needing to specify the token for each helm command or hardcoding it into `values.yaml`.
For clusters that utilize external secrets (such as https://github.com/external-secrets/kubernetes-external-secrets), charts that allow providing an existing secret provide the functionality needed to remove all sensitive information from the chart files themselves.
These changes are an attempt to implement similar functionality that bitnami has in many of their charts. For example. the [redis chart](https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L101)

Allow Komodor api key to be provided by an existing kubnernetes secret

---

charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/templates/deployment.yaml

Done in order to allow for the creation of temporary files on agent, since write permissions were revoked on the agent container for security concerns.

Add tmp directory as volume in container

---

.buildkite/pipeline.yml

every agent installation overrides the pod exec configuration - this change will make sure the configuration is applied on new installations as well

CU-860pncvw1 - enabled pod exec on komodor's production agent

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml

The previous `gt` condition syntax was breaking old helm versions and resulted:
`Error: template: k8s-watcher/templates/clusterrole.yaml:433:57: executing "k8s-watcher/templates/clusterrole.yaml" at <gt>: wrong number of args for gt: want 2 got 0`
This is the fix for that.

CU-860q0eueg: Fix k8s-watcher clusterrole new condition to support older helm versions

---

charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/values.yaml

related ticket / context: https://app.clickup.com/t/860pzd63e
TLDR: client can't install the helm chart due to missing size limit on the volume
added the size limit + added an option to change it via the values.yaml file
I did not add the value to the readme following the fact that the `helm.enableActions` was not mentioned there
tested locally with no value on the values.yaml + value and made sure all paths work as expected
public: added volume size limit to the helm metadata emptyDir

added volume size limit to the helm metadata empty dir

---

.buildkite/pipeline.yml

motivation:
avoid situations where the upgrade would fail after bumping the version and releasing a failed upgrade to github pages

feat: run dry-run upgrade before release procedure

---

charts/k8s-watcher/charts/network-mapper/values.yaml

network mapper images for both deployment and daemonset were hosted on docker-hub which is causing issues to some of our customers reaching dockerhub limits.
also, the latest default tag in their chart could potentially cause breaking changes.
i uploaded the images to ECR and checked on production that deployment\daemonset are working and validated that we get rows in `event_networkmap_changes` @shaicantor - is there anything else i should do to check that we're still working?

feat: pin version to v0.1.17 on public-ecr

---

charts/k8s-watcher/templates/daemonset.yaml

public: add support in metrics agent to receive cluster name from configuration

CU-860quknkk - Support configured cluster name

---

charts/k8s-watcher/templates/configmap-daemon.yaml

We need this data in order to summarize it, then use it to calculate the cluster scope cost, in terms of allocation.

CU-860qwu0c2: Add node capacity metrics

---

charts/k8s-watcher/values.yaml

motivation:
currently the metrics daemonset is not running on nodes that have taints since the default toleration we set is empty
this PR adds a wildcard toleration on the daemonsset that will allow the pods to be scheduled on all cluster nodes
public: 
added a toleration on the daemonset to allow metrics daemon set pods to be scheduled on all nodes

CU-85zt5jfu0 - added wildcard toleration for metrics daemon set

---

Makefile
charts/k8s-watcher/README.md

* Add to generate-kube the cluster name
* Update the readme file.

CU-85ztcd9pw - fix missing clustername in generate kube templates

---

charts/k8s-watcher/templates/metrics/configmap-daemon.yaml
charts/k8s-watcher/templates/metrics/daemonset.yaml

The user experienced an error in the daemon logs : 
` Error in plugin: error making HTTP request to "https://${NODE_NAME}:10250/stats/summary": Get "https://${NODE_NAME}:10250/stats/summary": dial tcp: lookup ${NODE_NAME} on 172.20.0.10:53: no such host`
From what I saw online the solution is not trying to use the DNS server to resolve the node name but to use the internal node IP instead 
public: fix error with node DNS translation

CU-85ztknh8x - fix error when daemon cant translate mode dns

---

.buildkite/pipeline.yml
.buildkite/pipeline_scripts/publish_helm_charts.sh
.buildkite/tests/Makefile
.buildkite/tests/basic_test.py
.buildkite/tests/fixtures.py
.buildkite/tests/helpers/komodor_helper.py
.buildkite/tests/helpers/kubernetes_helper.py
.buildkite/tests/legacy_k8s_versions_test.py
.buildkite/tests/values_capabilities_events_test.py
scripts/helm-migration/Makefile
scripts/helm-migration/main.go
scripts/helm-migration/mapping.go
scripts/helm-migration/release-note.md

* Update basic test to check for errors in k8s-watcher logs (validated it detects the CSI Storage issue fixed yesterday)
* Add a new test to check for agent logs in old k8s versions (1.23 & 1.25)
* Fix bug in `publish` script
* Fix a bug in the mapping of the migration script
* Add a `release` target in the migration script makefile to create a draft release in case we will need to release more versions.

Komodor agent helm tests update

---

.buildkite/vulnerability-scan/exclude.yaml

Exclude vulnerabilities alert in `kubectl`, `helm`, and `pluto` till the end of the month.

CU-865d8zhvn - [skip-ci] Exclude several vulnerabilities till 31/10/2023

---

.buildkite/pipeline_scripts/legacy_bump_version.sh
charts/komodor-agent/README.md
charts/komodor-agent/templates/clusterrole.yaml
charts/komodor-agent/templates/configmap.yaml
charts/komodor-agent/values.yaml

Enable secrets by default when helm capability is enabled.
Allow deleting all resources when helm capability is enabled (Allow * delete in cluster role). 
Do not bump k8s-watcher chart version if not needed.

Helm uninstall not working due to lack permissions

---

.buildkite/pipeline_scripts/bump_version.sh
.buildkite/pipeline_scripts/create_gh_pre_release.sh

Create the tag on top of the bump version commit.
Since the tag was created before the bump-version commit, we were missing the new agent version....
Print verbose info in create_gh_pre_release.sh for debugging

[skip ci] fix: Missing info in pre-release body

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/templates/metrics/init-container.yaml
charts/k8s-watcher/values.yaml
charts/komodor-agent/README.md
charts/komodor-agent/templates/metrics/_containers.tpl
charts/komodor-agent/templates/node-enricher/_containers.tpl
charts/komodor-agent/templates/watcher/_containers.tpl
charts/komodor-agent/values.yaml

Move to `komodor-agent` unified image instead of `watcher`, `daemon`, `supervisor` and `node_enricher` images
CU-860t38uyf

[skip ci] Unified komodor-agent image

---

.buildkite/vulnerability-scan/exclude.yaml
.buildkite/vulnerability-scan/main.py

There was a change in the return data from Mend cli,
Previously we have every time the key `securityFindings.vulnerabilities` however now in case there are no vulnerabilities this key not exist in the returned data.
In addition, I've extended the exclusion of Pluto till next month.

[skip ci] fix(vulnerability scan): Error when no vuln detected

---

charts/komodor-agent/templates/metrics/configmap-daemon.yaml

we need the restarts total for each container to support the reliability check
cantor found out this field exists in the kube inventory plugin
we tested on staging - changed the configmap and restarted the daemon set  -> we saw restarts_count is added to the staging timestream DB

added restarts total to metrics collector inventory plugin

---

.buildkite/pipeline_scripts/create_gh_draft_release.sh
.buildkite/release_checks/pipeline/generate.py

* Add the list of images used in the charts to be part of the RN. This request came from CS to assist customers who need to transfer our images into a local repo.
* Fix a bug in the pipeline generation due to the change of `+RC` to `-RC`

CU-86bx2d9ge - chore(ci): Add list of images to the release-note and fix pipeline generation

---

.buildkite/tests/values_capabilities_proxy_test.py
.buildkite/vulnerability-scan/exclude.yaml
charts/komodor-agent/templates/metrics/_containers.tpl

* Add proxy variables to daemonset init-container in case proxy is enabled.
* Update proxy tests.
* Extend `pluto` vulnerability exclusion
CU-86bxd3jq5

fix(chart/komodor-agent): daemonset not starting when configuring proxy

---

.buildkite/tests/values_components_test.py
charts/komodor-agent/README.md
charts/komodor-agent/templates/_helpers.tpl
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/daemonset_windows.yaml
charts/komodor-agent/templates/deployment.yaml
charts/komodor-agent/templates/serviceaccount.yaml
charts/komodor-agent/values.yaml

This PR introduces support for custom labels in the komodor-agent Helm chart. Users can now provide custom labels for various resources, including Deployment, DaemonSet, and DaemonSet-Windows.
Changes:
* Deployment: Added support for custom labels.
* DaemonSet: Added support for custom labels.
* DaemonSet-Windows: Added support for custom labels.
Changelog:
* Added labels to values.yaml.
* Created a helper function for label management.
* Included the custom labels in each resource template.
* Added tests to verify the correct application of custom labels.

feat(komodor-agent): Support custom labels

---

.buildkite/tests/legacy_k8s_versions_test.py
charts/komodor-agent/templates/watcher/_containers.tpl
charts/komodor-agent/templates/watcher/_helpers.tpl
charts/komodor-agent/templates/watcher/_volumes.tpl

* Fix the wrong container name when enabling `enableMemLimitChecks`
* Fix the wrong value check if Helm is enabled.
* Update CI `legacy k8s versions` test to check for k8s-version 1.27

Fix(komodor-agent): Wrong values

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/configmap.yaml
charts/komodor-agent/templates/watcher/_containers.tpl
charts/komodor-agent/values.yaml

* Pass `tags` configuration in the config file instead of environment variable
* Fix parsing of tags when provided as a string with semicolon delimiter

CU-86c081bq5 - Fix formatting of Tags when passed as helm values as string or as map

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/deployment.yaml
charts/komodor-agent/templates/node-enricher/_containers.tpl
charts/komodor-agent/templates/watcher/_containers.tpl
charts/komodor-agent/values.yaml

cu-86c0ccq6k  - OPA Violations -  Configure Liveness and Readiness Probes for node-enricher
cu-86c0ccpfj - OPA Violation - Set Resource Quotas for init-daemon and init-cert
cu-86c0ccmyv  - OPA Violation - Security Context - komodor-agent
fixes for OPA violations on liveness\readiness probes\ resource qoutas and security context missing

chore: address opa violations

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/clusterrole.yaml
charts/komodor-agent/values.yaml

Some accounts have security policies that require teams to validate changes in Kubernetes RBAC. By not creating RBAC, the Helm chart will avoid generating any cluster roles or bindings. However, modifying RBAC places full responsibility on the account for managing permission errors, which can lead to unexpected behavior. This approach is not recommended and should be used with caution.

CU-86c0fwhr0 - feat: allow not creating rbac at all

---

charts/komodor-agent/Makefile
charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

This was in the past and probably was missed when we moved to the komodor-agent from the watcher
https://github.com/komodorio/helm-charts/blame/b3ea76976400b58fd4df1f513b1ea5fd4d5127d0/charts/k8s-watcher/values.yaml#L72

[CU-86c0x1d85] Add missing toleration on daemon

---

charts/komodor-agent/templates/watcher/_volumes.tpl

Mount the installed values into the watcher container,
Using the values will allow Komodor backend to have a better understanding of how the agent was installed
CU-86c0x044e

feat: Mount installed values into watcher container

---

.buildkite/tests/values_components_test.py
charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/daemonset_windows.yaml
charts/komodor-agent/templates/deployment.yaml
charts/komodor-agent/templates/deployment_metrics.yaml
charts/komodor-agent/values.yaml

Allow users to set a custom rolling update strategy for each resource
This pull request introduces support for configurable rolling update strategies. 
* Update the `README.md` to include descriptions for the new `strategy` and `updateStrategy` configuration options.
* Update the templates to override the default strategy when users set a custom strategy.
* Added a new test case: `test_override_update_strategy` to validate the rolling update strategy configuration for different components.

feat: support custom update strategy

---

publish.sh

This PR updates the pipeline to publish only the `Komodor-agent` Helm chart to the OCI registry.

[skip ci] - CU-86c16t7fu - fix(CD): Publish relevant charts to OCI registry

---

charts/komodor-agent/templates/clusterrole.yaml

- Moved the HPA permissions under the capabiliteis.actions value
- Added delete which we should add as an action in our platform
- Added create & update to align with other resources we give permissions in the capabilities.actions section (it's currently not required but might be used in the future?)

fixing hpa permissions to be included under capabilities.actions

---

charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
charts/komodor-agent/templates/metrics/configmap-daemon.yaml

Adds max , mean ,p90,p95,p99 and p75 aggregations to get more accurate results 
* Added `skip_processors_after_aggregators` - default now is false but from 1.4 the default value will change to true
* update fieldinclude to pass the aggregated fields 
* Introduced `aggregators.basicstats` and `aggregators.quantile` to perform statistical aggregation on metrics. [[1]](diffhunk://#diff-b39f2416903c6d23246a5a65e8b9f229f6c82f7b3e00a927af947c1f6794606aL30-R55) [[2]](diffhunk://#diff-c0903fd3cf76da60d2584e6dc9095d3e5dd0066abbefb28740de7c52c7d12c80L30-R56)
* Added `processors.regex` to rename fields based on patterns for backward compatibility. [[1]](diffhunk://#diff-b39f2416903c6d23246a5a65e8b9f229f6c82f7b3e00a927af947c1f6794606aL30-R55) …

CU-86c1z5mux  - add basicstats aggregator and regex processor to metrics confingmaps

---

charts/komodor-agent/templates/serviceaccount.yaml

when the following are specified:
- `serviceAccount.create: false`
- `serviceAccount.name: some-sa`
- `imagePullSecret: some-secret`
we are currently generating incorrect serviceaccount.yaml due to improper if blocks. This resolves that

CU-86c2f0mpdstop - serviceaccount template from generating when imagePullSecret is specified

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset_windows.yaml
charts/komodor-agent/values.yaml

This pull request includes changes to the `komodor-agent` Helm chart to remove the `hostNetwork` configuration for the Windows daemon since it's not supported on windows.

fix: remove hostNetwork parameter from komodorDaemonWindows configuration - not supported on windows

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

* Updated Telegraf image versions in the `values.yaml` file to `v1.34.1-build1-alpine` and `v1.34.1-build1-windows`.

security: bump versions

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
charts/komodor-agent/templates/metrics/configmap-daemon.yaml
charts/komodor-agent/values.yaml

This pull request includes changes to the `komodor-agent` Helm chart to add a new configuration option for setting the quiet mode for the komodor agent metrics. The most important changes include updates to the `README.md` file, the metrics configuration templates, and the `values.yaml` file.
* [`charts/komodor-agent/README.md`](diffhunk://#diff-a1c7c440ff8832984790b9cc6143fb153a3783a5e3074e6338e61365cf5a0f2aL208-R212): Added `quiet` option to the `components.komodorDaemon.metrics` and `components.komodorDaemonWindows.metrics` sections. [[1]](diffhunk://#diff-a1c7c440ff8832984790b9cc6143fb153a3783a5e3074e6338e61365cf5a0f2aL208-R212) [[2]](diffhunk://#diff-a1c7c440ff8832984790b9cc6143fb153a3783a5e3074e6338e61365cf5a0f2aL225-R230)
* …

feat: add quiet mode configuration for komodor agent metrics [CU-86c2kua4v]

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/metrics/_containers_deamon.tpl
charts/komodor-agent/templates/metrics/configmap-daemon.yaml
charts/komodor-agent/values.yaml

It add new `components.komodorDaemon.metrics.dcgm=true/false` value that enables collecting metrics from NVIDIA DCGM for GPU project. Disabled by default.
Tested on GPU demo cluster that it installs and functions OK.

CU-86c3chx0b Add flag to use new GPU metrics collecting

---

.buildkite/pipeline_scripts/production-values.yaml
.buildkite/pipeline_scripts/staging-values.yaml
charts/komodor-agent/templates/crd/klaudia.yaml

This pull request introduces changes to streamline event creation capabilities and conditional resource definition logic across various files. The most important changes include disabling event creation in specific environments and adding conditional logic for the creation of a custom resource definition (`CRD`) in Kubernetes.
* [`.buildkite/pipeline_scripts/production-values.yaml`](diffhunk://#diff-a104f7c8810e77e2b02cd35525fd1dd1dab78eb08859bff47f42cde19ca619b3R6-R7): Added `events.create: false` under `capabilities` to disable event creation in the production environment.
* [`.buildkite/pipeline_scripts/staging-values.yaml`](diffhunk://#diff-9fd4be794439138ee3073095e6e609b1c71006eb27393c12aa310269e36d320dR18-R19): Added `events.create: false` under `capabilities` to disable event …

CU-86c3rx3zc - chore: disable installation in staging and production

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/metrics/_containers_daemon.tpl
charts/komodor-agent/templates/metrics/_security.tpl
charts/komodor-agent/templates/metrics/_volumes.tpl
charts/komodor-agent/values.yaml

This PR adds an option to have on each node the "GPU access container" that is used by Klaudia to request the GPU diagnostical logs from host. The container has a lot of permissions, namely host root filesystem mounted.

CU-86c3runey - GPU diagnostics access container

---

charts/komodor-agent/templates/metrics/_containers_daemon.tpl

This change solves an issue that happens to bam & fispan 
We dont know the root cause yet 
But this simple change solves their issue and we want to include it in our next Komodor version

CU-86c3zc0kd - Add command for metrics container in daemonset template

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/_helpers.tpl
charts/komodor-agent/templates/crd/klaudia.yaml
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/daemonset_gpu.yaml
charts/komodor-agent/templates/metrics/_containers_daemon.tpl
charts/komodor-agent/templates/metrics/_volumes.tpl
charts/komodor-agent/values.yaml

Following up @nirbenator's comment on Slack:
we have a couple of refinements before we GA this
1. Separate the GPU container to a different daemonset to allow it to be set with a specific toleration for the following taint (we validated gke and eks but im not sure )
```
taints:
- effect: NoSchedule
key: nvidia.com/gpu
value: "true"
```
2. By default, don’t set the container as privileged and have it controlled by the components.komodorDaemon.gpuAccessContainer.enabled value (even though it is not installed by default - some helm chart scanners don’t like seeing security contexts with priviledge)
Can we please add this to the backlog and push this sometime before the end of the month ?

CU-86c40bu76 - Separate gpu accessor daemonset

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/daemonset_windows.yaml
charts/komodor-agent/templates/deployment_metrics.yaml
charts/komodor-agent/templates/metrics/_containers_daemon.tpl
charts/komodor-agent/templates/metrics/_containers_deployment.tpl
charts/komodor-agent/values.yaml

CU-86c4150pe
* Add configuration sidecar for daemon and metrics deployment to support dynamic config
* !!! Will need to update telegraf_init image tag, after that is released before merging this PR

Add sidecar config container to metrics daemon and deployment

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/configmap.yaml
charts/komodor-agent/templates/opentelemetry/_containers.tpl
charts/komodor-agent/templates/opentelemetry/_helpers.tpl
charts/komodor-agent/templates/opentelemetry/configmap.yaml
charts/komodor-agent/templates/opentelemetry/service.yaml
charts/komodor-agent/values.yaml

--------- Chart changes:
* Otel collector will now be deployed by default along with the agent
* If otel collector deployment is enabled, route agent telemetry to it instead of remote endpoint directly & disable remote log sink as otel collector gets them automatically via filelog
* Fix otel collector config mount path
* Include proxy configuration env vars for otel collector container
--------- Internal Monitoring:
* Created new log indexes for staging+production to organize what comes from this otel collector
* Updated in Datadog the startup/liveness metrics we generate from logs
* Checked that there's no critical monitors/alerts that were relying only on old log sources.
Tested deployment on actual cluster vs. production account

CU-86c4byh2t - Deploy OTEL Collector by default for internal telemetry

---

charts/komodor-agent/templates/NOTES.txt

Fix the docs link from `docs.komodor.com` to `help.komodor.com`

[skip-ci] fix cu-86c4jzxbv

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

* Update `markUnevictable` and `addNodeAffinityToMarkedPods` to be true by default
* It will still require customers to enable Pod Placement via the UI for each cluster they want it to affect.

CU-86c5h62kf - update binpacking configuration to true by default
