charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/Makefile
charts/k8s-watcher/README.md
charts/k8s-watcher/kube-install/k8s-watcher/templates/configmap.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/values.yaml

Prerequisite: https://github.com/komodorio/k8s-watcher/pull/6

Add health check

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/README.md
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
charts/k8s-watcher/values.yaml

Dependent on https://github.com/komodorio/k8s-watcher/pull/8

Add readme for clustername config

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/README.md
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml

Add documentation for how to use ARM images

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
charts/k8s-watcher/templates/deployment.yaml

related to https://github.com/komodorio/k8s-watcher/pull/47

feat: add podinfo with memory limit file

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
manifests/base/kustomization.yaml

Dependent on: https://github.com/komodorio/k8s-watcher/pull/68

Update agent to 0.1.50

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
manifests/base/kustomization.yaml

Requires: https://github.com/komodorio/k8s-watcher/pull/69

Update agent image to version 0.1.51

---

charts/k8s-watcher/kube-install/k8s-watcher/templates/configmap.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/values.yaml
manifests/overlays/full/komodor-k8s-watcher.yaml

Fix bad value name in helm chart

CU-2cj73g6 - Update new inspection configuration in kustomize

---

charts/k8s-watcher/README.md
charts/k8s-watcher/kube-install/k8s-watcher/templates/configmap.yaml
charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/values.yaml
manifests/base/komodor-k8s-watcher.yaml
manifests/overlays/full/komodor-k8s-watcher.yaml

add documentation for pod logs data redaction

---

.buildkite/pipeline.yml
publish.sh

removed a 30 second sleep waiting for helm repo to update with the new version
added validation that the version was actually updated

CU-860phernx - feat: pipeline change - wait for chart to be updated

---

.buildkite/pipeline.yml
.buildkite/validate_helm_chart_updated.py

validation for chart update before we continue to deploy
tested in branch run [here](https://buildkite.com/komodor/helm-charts/builds/799#0185b57e-0667-499f-9bad-40abf8c68e2d)

Validate chart is updated before installing agents

---

.github/workflows/publish-chart.yaml

Changes action version

---

.buildkite/pipeline.yml
charts/k8s-watcher/templates/_helpers.tpl
charts/k8s-watcher/templates/configmap-metrics.yaml
charts/k8s-watcher/templates/daemonset-metrics.yaml
charts/k8s-watcher/values.yaml

public: Add new metrics agent ( not active by default )

CU-860q4n8y4 -add charts

---

charts/k8s-watcher/Chart.yaml

CU-860q3e8h9 - update version of agent

---

charts/k8s-watcher/templates/daemonset-metrics.yaml

public: update env var for new metrics agent

CU-860q3e8h9 - update secret as env var

---

charts/k8s-watcher/templates/configmap-metrics.yaml
charts/k8s-watcher/templates/daemonset-metrics.yaml

public: support backwards compatibility for metrics config

CU-860q9a2pz - Update if condition

---

charts/k8s-watcher/templates/daemonset-metrics.yaml

public: metrics agent image config update

CU-860q9q81c - add image pull policy

---

charts/k8s-watcher/templates/configmap-metrics.yaml

CU-860qa4mvb - update metrics fields

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml

public: add minimal permissions for metrics agent

CU-860qa4tdb - add permissions for metrics

---

charts/k8s-watcher/kube-install/k8s-watcher/templates/configmap.yaml
charts/k8s-watcher/templates/_helpers.tpl
charts/k8s-watcher/templates/configmap-metrics.yaml
charts/k8s-watcher/templates/daemonset-metrics.yaml
charts/k8s-watcher/values.yaml

CU-860qa4tx6 - rename metrics agent

---

charts/k8s-watcher/templates/configmap-daemon.yaml
charts/k8s-watcher/templates/daemonset.yaml

CU-860qc67zp - rename files and backward compatibility

---

charts/k8s-watcher/values.yaml

public: update metrics agent docker image

CU-860q4n90m - update metrics image docker repo

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml

CU-860qghbvj - update cluster role condition

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml
charts/k8s-watcher/templates/configmap-daemon.yaml

CU-860qj1bmd - add config to monitor all namespaces and not just default

---

charts/k8s-watcher/values.yaml

public: update daemon config value

CU-860qjcbjw - copy metrics.enabled config to watcher.daemon.enabled for UI agent installed check 

---

charts/k8s-watcher/templates/_helpers.tpl
charts/k8s-watcher/templates/configmap.yaml
charts/k8s-watcher/values.yaml

CU-860qjr91h - add config to configmap

---

charts/k8s-watcher/templates/configmap-daemon.yaml

Cu-860qjrda7 telegraf http

---

charts/k8s-watcher/templates/configmap-daemon.yaml

CU-860qqcthg - zip data

---

charts/k8s-watcher/values.yaml

public: Increase daemon memory request and limit to 256Mi

Increase daemon memory request and limit to 256Mi

---

charts/k8s-watcher/templates/configmap-daemon.yaml
charts/k8s-watcher/templates/daemonset.yaml

public: Support proxies in daemonset

Cu-860qqrfeg daemon proxy support

---

charts/k8s-watcher/templates/NOTES.txt

[skip ci] On to in in the NOTES.txt file

---

charts/k8s-watcher/templates/configmap-daemon.yaml

public: add timeout config to metrics limits collection

CU-860qwrwvk - Update daemon configmap

---

charts/k8s-watcher/templates/_helpers.tpl
charts/k8s-watcher/templates/configmap-daemon.yaml

public: support configurable server host

CU-85zt2z5nm - add use server host

---

charts/k8s-watcher/templates/daemonset.yaml

public: add priority class to daemon

CU-862jx026u - add priority class to daemon helm charts

---

charts/k8s-watcher/values.yaml

public: move cluster name comment location

CU-85zta1qhu - update cluster name location

---

charts/k8s-watcher/templates/metrics/configmap-daemon.yaml

CU-85ztek2km - add timeout to http output

---

charts/k8s-watcher/templates/metrics/init-container.yaml
charts/k8s-watcher/values.yaml

public: add default resources  for init container

CU-85ztfa9yf - add init resources

---

charts/k8s-watcher/values.yaml
scripts/network-mapper/update-ecr.sh

public: upgrade network-mapper and sniffer to latest version 0.1.26

upgraded network-mapper and sniffer to latest version 0.1.26

---

charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/templates/metrics/configmap.yaml
charts/k8s-watcher/templates/metrics/deploy.yaml

public: improve metric collection performance

CU-860rdgtu0 - separate metrics inventory plugin into deploy

---

charts/k8s-watcher/templates/metrics/deploy.yaml

public: fix a bug in metrics volume names

CU-85ztrv21p - fix deploy

---

charts/k8s-watcher/templates/metrics/deploy.yaml

CU-85ztrv21p - fix deploy - revert

---

charts/k8s-watcher/templates/deployment.yaml
charts/k8s-watcher/templates/metrics/deploy.yaml

public: remove duplicate config

CU-85ztrw3we - update charts

---

charts/k8s-watcher/templates/deployment.yaml

CU-85ztrwth9 - fix deploy

---

charts/k8s-watcher/templates/deployment.yaml

CU-85ztrwyz8 - fix name

---

charts/k8s-watcher/templates/_helpers.tpl
charts/k8s-watcher/templates/metrics/configmap.yaml
charts/k8s-watcher/values.yaml

public: add api server url configuration to values

CU-85zttjvr1 - make api server url configurable

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml
charts/k8s-watcher/templates/metrics/configmap-daemon.yaml
charts/k8s-watcher/templates/metrics/configmap.yaml
charts/k8s-watcher/templates/metrics/daemonset.yaml
charts/k8s-watcher/templates/metrics/deploy.yaml
charts/k8s-watcher/templates/metrics/init-container.yaml
charts/k8s-watcher/templates/network-mapper/cluster-role.yaml
charts/k8s-watcher/templates/network-mapper/configmap.yaml
charts/k8s-watcher/templates/network-mapper/daemonset.yaml
charts/k8s-watcher/templates/network-mapper/deployment.yaml
charts/k8s-watcher/templates/network-mapper/role.yaml
charts/k8s-watcher/templates/network-mapper/roles-binding.yaml
charts/k8s-watcher/templates/network-mapper/service.yaml

Fix template if condition that enables/disables the network-mapper

CU-85ztv4pr8 - Fix network mapper cannot be disabled

---

charts/k8s-watcher/templates/network-mapper/daemonset.yaml
charts/k8s-watcher/templates/network-mapper/deployment.yaml
charts/k8s-watcher/values.yaml

Update network mapper to version `0.1.29`

CU-85ztv6c2d - update network mapper version

---

charts/k8s-watcher/templates/metrics/daemonset.yaml
charts/k8s-watcher/templates/metrics/deploy.yaml
charts/k8s-watcher/values.yaml

public: upgrade telegraf version

CU-85ztwhxt6 - upgrade telegraf version

---

charts/k8s-watcher/templates/network-mapper/daemonset.yaml
charts/k8s-watcher/templates/network-mapper/deployment.yaml
charts/k8s-watcher/values.yaml

public: Bump network mapper version

CU-85ztxta7q - Bump network-mapper version to v0.1.32

---

charts/k8s-watcher/templates/network-mapper/daemonset.yaml

public: Fix network-mapper condition check

CU-85ztzp8u5 - Fix network-mapper condition check

---

charts/k8s-watcher/Chart.yaml
charts/k8s-watcher/templates/clusterrole.yaml

public: update cluster roles for metrics

CU-860rpu48a - update cluster role to access kubelet

---

.buildkite/pipeline.yml

1. fix the missing namespace in one pipeline step
2. Verify full release flow

CU-865d83p3u - First full release of komodor-agent

---

.buildkite/vulnerability-scan/exclude.yaml
.buildkite/vulnerability-scan/main.py

* Fix filtering error
* Extend exclusions time

[skip-ci] CU-86792qq85 - fix error when scanning telegraf image

---

.buildkite/validate_helm_chart_updated.py

* support RC versions
* + Refactor the script

CU-8679415e9 - update validate_helm_chart_updated.py to support RC versions

---

charts/komodor-agent/values.yaml
scripts/helm-migration/main.go

* Move communications  to the bottom of the values file
* Add `--create-namespace`  to the migrations script

Changes after CS review - CU-860rzrtfh

---

charts/k8s-watcher/values.yaml

Enable network mapper by default for new installations

CU-8679727dy - feat: Enable network-mapper by default

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/values.yaml

Use different node affinity between deployment and daemonset
Remove resources from the metrics daemon

CU-867981mn2 - Bugfixes from POC inputs

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

Remove limits from metrics daemon,
same as we have in k8s-watcher chart

CU-867986mhv - Remove limits from metrics daemon

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

We checked the P95 from timestream for all customer and decided on suitable values.

CU-86798y3bd - set resources for metrics container

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset.yaml
charts/komodor-agent/templates/node-enricher/_containers.tpl
charts/komodor-agent/values.yaml

public: Install node-enricher service as part of the komodor-agent daemonset

Add node-enricher to komodor-agent chart

---

charts/komodor-agent/templates/node-enricher/_containers.tpl

public: Add api key as environment variable to the node enricher container

CU-866b30503 - add api-key to node enricher container

---

.buildkite/pipeline.yml
.buildkite/tests/ci/use-new-agent-version.sh

Set the agent version in Chart.yaml before the test.

[skip ci] - fix(test): testing wrong agent version

---

.buildkite/pipeline.yml
.buildkite/pipeline_scripts/bump_version.sh
.buildkite/pipeline_scripts/update_agent.sh
.buildkite/pipeline_scripts_tests/bump_version_test.bat
.buildkite/validate_helm_chart_updated.py

* Change RC version tagging from `+RC` to `-RC` to proper support semVer
* Add tests to bump_version.sh script
CU-86bww1yjb

[skip ci] Change RC version from +RC to -RC to support proper semVer

---

.buildkite/pipeline.yml
.buildkite/pipeline_scripts/legacy_test_helm_new_install.sh
.buildkite/pipeline_scripts/legacy_test_helm_update_install.sh
.buildkite/pipeline_scripts/staging-values.yaml
.buildkite/tests/values_capabilities_proxy_test.py
.buildkite/tests/values_capabilities_test.py
.buildkite/tests/values_components_test.py
.gitignore
charts/komodor-agent/values.yaml

Related to: https://github.com/komodorio/komodor-agent/pull/335
CU-860qv9ngg

cfg: add mgmtServerHost communications configuration

---

.buildkite/tests/values_capabilities_test.py
charts/komodor-agent/templates/configmap.yaml
charts/komodor-agent/templates/watcher/_containers.tpl

Fixes https://github.com/komodorio/helm-charts/issues/293 and https://github.com/komodorio/helm-charts/issues/291

CU-86bx2kutq - fix: Allow multiline values, fix resources mapping for supervisor container

---

charts/komodor-agent/templates/clusterrole.yaml

add edit role to hpa in clusterrole.yaml

CU-3bfn5zu - allow edit and delete hpa

---

charts/komodor-agent/templates/clusterrole.yaml

CU-3bfn5zu - allow to patch hpa

---

charts/komodor-agent/README.md
charts/komodor-agent/README.md.gotmpl

change from intercom to help center

[skip ci] Update help center link in readme

---

.buildkite/pipeline.yml
publish.sh

* Push helm chart as OCI artifact to docker-hub registry.
* Refactor the `publish.sh` script for better readability & maintainability.

chore(CD): Publish helm chart to docker-hub

---

.buildkite/vulnerability-scan/main.py

Exclude the windows-telegraf image from being scanned by mend

[skip ci]- chore(mend): Exclude windows-telegraf image

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/daemonset_windows.yaml
charts/komodor-agent/templates/metrics/_containers.tpl
charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
charts/komodor-agent/templates/metrics/configmap-daemon.yaml
charts/komodor-agent/values.yaml

Add support for windows metrics daemon with komodor custom metrics plugin

Telegraf custom plugin windows

---

charts/komodor-agent/README.md
charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
charts/komodor-agent/templates/metrics/configmap-daemon.yaml
charts/komodor-agent/values.yaml

Update telegraf image to a version supporting poll_interval
Add poll_interval to configmap

Cu 86by9b9xp support gather interval

---

.buildkite/pipeline_scripts/production-values.yaml

enable datadog profiling for our production agent

---

.buildkite/pipeline_scripts/production-values.yaml

Necessary for more stable profiling

CU-86bz7uwhh - deploy prod agent on on demand instances

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

* Update telegraf version to 1.32.3

Cu 86c13cj5w upgrade telegraf v.1.32.3

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

Update WIndows daemon to new version based on servercore

Cu 86c1ub4hh windows daemon

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

This pull request includes an update to the Telegraf image version in the `charts/komodor-agent/values.yaml` file.
* Updated `telegrafImageVersion` to `v1.33.1-alpine` from `v1.32.3-alpine` to ensure the latest features and security patches are included.

CU-86c1x2ce7 - chore: update to version 1.33.1

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

https://github.com/influxdata/telegraf/releases/tag/v1.33.2

Cu-86c1xeb56 chore: update telegraf image version to v1.33.2-alpine

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

https://github.com/komodorio/mono/pull/19001#pullrequestreview-2697855765

feat: add rbac-cluster-sync params

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

Itiel asked to enable it by default

CU-86c3m8rev - Change default of DCGM to true

---

charts/komodor-agent/templates/clusterrole.yaml

add required cluster role permissions for admission controller if enabled

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

https://github.com/komodorio/admission-controller/releases/tag/0.0.6
https://github.com/komodorio/telegraf-plugins/releases/tag/v1.34.4-build1

CU-86c3wgdvd - Update version of admission controller and telegraf plugins

---

charts/komodor-agent/templates/admission-controller/deployment.yaml
charts/komodor-agent/values.yaml

add missing deployment annotations, add config checksum for auto-reloading, update admission-controller to latest release

---

charts/komodor-agent/templates/admission-controller/deployment.yaml

add a checksum to automatically refresh controller server with new certificates and configuration if they change

---

charts/komodor-agent/README.md
charts/komodor-agent/values.yaml

Related to komodorio/mono#21555

CU-86c50xgrq - update telegraf to v2.0.6 + admission controller to 0.1.9

---

charts/komodor-agent/README.md
charts/komodor-agent/README.md.gotmpl
charts/komodor-agent/utilities/memory-planning/01-namespace.yaml
charts/komodor-agent/utilities/memory-planning/02-configmap.yaml
charts/komodor-agent/utilities/memory-planning/03-serviceaccount.yaml
charts/komodor-agent/utilities/memory-planning/04-clusterrole.yaml
charts/komodor-agent/utilities/memory-planning/05-clusterrolebinding.yaml
charts/komodor-agent/utilities/memory-planning/06-job.yaml
charts/komodor-agent/utilities/memory-planning/README.md

add memory checker utility to check recommended memory requirements

---

charts/komodor-agent/templates/admission-controller/rbac.yaml
charts/komodor-agent/templates/admission-controller/webhookconfiguration.yaml
charts/komodor-agent/values.yaml

This PR depends on [this AC PR](https://github.com/komodorio/admission-controller/pull/35), which is already merged but should be released before we merge *this* PR.

Support Spark in rightsizing webhook: reinvocation policy + RBAC
